// <auto-generated />
using System;
using DBShopSite.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DBShopSite.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180820073520_part6")]
    partial class part6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DBShopSite.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("Command")
                        .HasMaxLength(32);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<int>("ParentId");

                    b.Property<int>("Status");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Menu");

                    b.HasData(
                        new { Id = 1, Code = "main", Command = "Main", Name = "Головна", ParentId = 0, Status = 1 },
                        new { Id = 2, Code = "Rods", Command = "", Name = "Вудилища", ParentId = 0, Status = 1 },
                        new { Id = 3, Code = "Reels", Command = "", Name = "Катушки", ParentId = 0, Status = 1 },
                        new { Id = 4, Code = "Accessories", Command = "", Name = "Аксесуари", ParentId = 0, Status = 1 },
                        new { Id = 5, Code = "FeederRods", Command = "FeederRods", Name = "Фідерні удилища", ParentId = 2, Status = 1 },
                        new { Id = 6, Code = "SpiningRods", Command = "SpiningRods", Name = "Спінінгові удилища", ParentId = 2, Status = 1 },
                        new { Id = 7, Code = "FeederReels", Command = "FeederReels", Name = "Фідерні катушки", ParentId = 3, Status = 1 },
                        new { Id = 8, Code = "FloadReels", Command = "FloadReels", Name = "Поплавочні катушки", ParentId = 3, Status = 1 },
                        new { Id = 9, Code = "SpiningReels", Command = "SpiningReels", Name = "Спінінгові катушки", ParentId = 3, Status = 1 }
                    );
                });

            modelBuilder.Entity("DBShopSite.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleCode");

                    b.Property<string>("RoleName");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new { Id = 1, RoleCode = "Admin", RoleName = "Адміністратор", Status = 1 },
                        new { Id = 2, RoleCode = "Guest", RoleName = "Гість", Status = 1 },
                        new { Id = 3, RoleCode = "Client", RoleName = "Клієнт", Status = 1 }
                    );
                });

            modelBuilder.Entity("DBShopSite.Entities.RolesMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MenuId");

                    b.Property<int>("RoleId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolesMenu");
                });

            modelBuilder.Entity("DBShopSite.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment")
                        .HasMaxLength(250);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<int?>("Status")
                        .IsRequired();

                    b.Property<string>("eMail")
                        .HasMaxLength(70);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Login = "Guest", Name = "Гість", Status = 1 },
                        new { Id = 2, Login = "VIvanchuk", Name = "Іванчук Володимир Львович", Status = 1 }
                    );
                });

            modelBuilder.Entity("DBShopSite.Entities.UsersRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RoleId");

                    b.Property<int>("Status");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UsersRoles");
                });

            modelBuilder.Entity("DBShopSite.Entities.RolesMenu", b =>
                {
                    b.HasOne("DBShopSite.Entities.Menu")
                        .WithMany("MenusRoles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DBShopSite.Entities.User")
                        .WithMany("UsersRoles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DBShopSite.Entities.Roles")
                        .WithMany("RolesMenu")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
